"""The tour must keep producing its committed output byte for byte.

The card-family fixtures under tests/fixtures/golden/ are rendered through the
card engine, which the tour has no THEME for, so the tour's fixture sits in
tests/fixtures/golden_tour/ and is regenerated by scripts/regen_tour_golden.py
rather than scripts/regen_golden.py.
"""
import pathlib
import re
import sys

import pytest

sys.path.insert(0, str(pathlib.Path(__file__).parent.parent / "scripts"))

from regen_tour_golden import render_into  # noqa: E402

FIXTURE = pathlib.Path(__file__).parent / "fixtures" / "golden_tour"
COMMITTED = sorted(p.name for p in FIXTURE.iterdir() if p.name != "input.json")


def _rendered(tmp_path):
    render_into(tmp_path)
    return {p.name: p.read_text(encoding="utf-8") for p in tmp_path.iterdir()}


def test_the_fixture_covers_every_file_the_tour_writes():
    assert COMMITTED, "no committed tour fixture; regenerate with scripts/regen_tour_golden.py"
    assert "index.html" in COMMITTED and "index.md" in COMMITTED
    assert "01_queue_reader.html" in COMMITTED and "02_ledger_writer.html" in COMMITTED


@pytest.mark.parametrize("name", COMMITTED)
def test_golden_tour_output(name, tmp_path):
    assert _rendered(tmp_path)[name] == (FIXTURE / name).read_text(encoding="utf-8")


def test_the_tour_renders_no_more_and_no_fewer_files_than_committed(tmp_path):
    assert sorted(_rendered(tmp_path)) == COMMITTED


# The fixture's repo name, chapter name and one file path carry these. Chapter
# names come from the Analyze pass over the target repo's own files and the
# paths come straight out of that repo, so both are untrusted; the fixture is
# hostile on purpose, to hold the escaping on every sink they reach.
HOSTILE = ("<script>alert(1)</script>", "<img src=x onerror=alert(1)>")


@pytest.mark.parametrize("name", [n for n in COMMITTED if n.endswith(".html")])
def test_no_committed_page_carries_an_unescaped_name_or_path(name):
    """Every sink that takes a chapter name, a repo name or a file path.

    Without a hostile fixture each html.escape() on those is a no-op and can be
    deleted with the suite still green -- this project has shipped a stored-XSS
    bug once already.
    """
    page = (FIXTURE / name).read_text(encoding="utf-8")
    for payload in HOSTILE:
        assert payload not in page, f"{name} carries {payload!r} as live markup"
    assert "&lt;script&gt;alert(1)&lt;/script&gt;" in page, (
        f"{name} never received the hostile repo or chapter name, so it proves nothing")


def test_the_hostile_path_reaches_the_file_list_escaped():
    """The index is the only page listing selected_files, so it is checked alone."""
    page = (FIXTURE / "index.html").read_text(encoding="utf-8")
    assert "&lt;img src=x onerror=alert(1)&gt;.py" in page
    assert "onerror=alert(1)>.py" not in page


def test_the_committed_pages_carry_the_shared_visual_layer():
    """A fixture check, not a renderer check: it reads the committed bytes, so
    it catches a fixture regenerated from a renderer that had lost the layer."""
    for name in ("index.html", "01_queue_reader.html"):
        page = (FIXTURE / name).read_text(encoding="utf-8")
        assert "family=Inter" in page, f"{name} lost the web fonts"
        assert "highlight.min.js" in page, f"{name} lost syntax highlighting"
        assert "prefers-color-scheme: dark" in page, f"{name} lost dark mode"
        assert "securityLevel: 'strict'" in page, f"{name} lost the mermaid sanitiser"


def test_the_committed_chapter_highlights_code_and_keeps_diagrams_separate():
    """highlight.js reads `pre code`; a mermaid block must not have one, or the
    highlighter would rewrite the diagram source before mermaid parses it."""
    page = (FIXTURE / "02_ledger_writer.html").read_text(encoding="utf-8")
    assert '<code class="language-go">' in page
    diagrams = re.findall(r'<pre class="mermaid">(.*?)</pre>', page, re.S)
    assert diagrams, "the chapter's mermaid fence did not become a diagram block"
    for src in diagrams:
        assert "<code" not in src, f"a diagram block carries a code element: {src[:80]}"
    assert "language-mermaid" not in page
