#!/usr/bin/env python3
"""Regenerate a golden render fixture from the sibling port source.

The golden files under tests/fixtures/golden/<analysis>/ pin the exact HTML and
markdown a ported analysis produces for a fixed `shared` dict. They are
generated from the port source of record, not from crack itself, so the test
proves the port stayed faithful rather than proving crack agrees with itself.

Use it when a deliberate change to the card engine or to an analysis's THEME or
SECTIONS makes a golden test fail. Never use it to silence an unexplained
failure -- diff the output first and know why it moved.

    scripts/regen_golden.py backend
    scripts/regen_golden.py backend --sibling ~/code/Crack-Any-Codebase-with-AI

The sibling checkout must be on the pinned port-source commit; the script
refuses to run otherwise. See docs/superpowers/specs/2026-09-01-analysis-port-design.md.

Run this with the sibling checkout's own Python, not `uv run` -- that activates
this project's venv, where coderay's own `crack` package is installed, and an
import of `crack` would silently resolve there instead of the sibling.
"""
import argparse
import json
import os
import pathlib
import subprocess
import sys

PORT_SOURCE_COMMIT = "d2bf6963f621a78b9ea3ac73268e1386a982df9d"
DEFAULT_SIBLING = pathlib.Path.home() / "code" / "Crack-Any-Codebase-with-AI"
GOLDEN = pathlib.Path(__file__).resolve().parent.parent / "tests" / "fixtures" / "golden"

def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("analysis", help="the analysis to regenerate, e.g. backend")
    ap.add_argument("--sibling", type=pathlib.Path, default=DEFAULT_SIBLING,
                    help=f"port source checkout (default: {DEFAULT_SIBLING})")
    ap.add_argument("--allow-any-commit", action="store_true",
                    help="skip the pinned-commit check (you must say why in the commit message)")
    args = ap.parse_args()

    out_dir = GOLDEN / args.analysis
    shared_path = out_dir / "shared.json"
    if not shared_path.is_file():
        sys.exit(f"no fixture input at {shared_path}")

    head = subprocess.run(["git", "-C", str(args.sibling), "rev-parse", "HEAD"],
                          capture_output=True, text=True).stdout.strip()
    if head != PORT_SOURCE_COMMIT and not args.allow_any_commit:
        sys.exit(f"{args.sibling} is at {head or '(not a git checkout)'}, "
                 f"expected the pinned port source {PORT_SOURCE_COMMIT}.\n"
                 f"Check it out, or pass --allow-any-commit deliberately.")

    sys.path.insert(0, str(args.sibling / "src"))
    import crack as _crack

    resolved = os.path.realpath(_crack.__file__)
    sibling_root = os.path.realpath(str(args.sibling))
    if not resolved.startswith(sibling_root + os.sep):
        sys.exit(f"imported crack from {resolved}, not under {sibling_root}.\n"
                 f"This means the sibling's crack package was shadowed by another "
                 f"installed crack (likely this project's own venv). Refusing to "
                 f"write golden files generated by the wrong package. Run this "
                 f"script with a plain python interpreter, not `uv run`.")
    print(f"using crack from {resolved}")

    from crack.analyses import load           # the sibling's registry, not ours
    from crack.core import render

    analysis = load(args.analysis)
    shared = json.loads(shared_path.read_text(encoding="utf-8"))
    (out_dir / "index.html").write_text(render.render_html(analysis, "toy_repo", shared), encoding="utf-8")
    (out_dir / "index.md").write_text(render.render_markdown(analysis, "toy_repo", shared), encoding="utf-8")
    print(f"wrote {out_dir}/index.html and {out_dir}/index.md from {args.sibling} @ {head[:7]}")

if __name__ == "__main__":
    main()
